/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Contrats: () => import('#controllers/contrats_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  StockItems: () => import('#controllers/stock_items_controller'),
  Stocks: () => import('#controllers/stocks_controller'),
}
